import { writeFileSync } from 'node:fs';
import { feature } from 'topojson-client';

const SOURCE = 'https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json';
const OUT = new URL('../src/game/data/countries.ts', import.meta.url);
const SEP = '|~|';

const SKIP = new Set(['Antarctica', 'Fr. S. Antarctic Lands', 'Greenland', 'Falkland Is.']);

type Ring = [number, number][];
interface Feature {
  properties?: { name?: string };
  geometry?: { type?: string; coordinates?: unknown };
}

const round = (v: number): number => Math.round(v * 10) / 10;

function toRings(geometry: Feature['geometry'] | undefined): Ring[] {
  const out: Ring[] = [];
  if (geometry === undefined) return out;
  const raw = geometry.coordinates;
  const polygons: unknown[] =
    geometry.type === 'Polygon' ? [raw] : geometry.type === 'MultiPolygon' ? (raw as unknown[]) : [];

  for (const polygon of polygons) {
    for (const ring of polygon as Ring[]) {
      const cleaned: Ring = [];
      for (const [lon, lat] of ring) {
        if (Number.isFinite(lon) && Number.isFinite(lat)) cleaned.push([round(lon), round(lat)]);
      }
      if (cleaned.length >= 4) out.push(cleaned);
    }
  }
  return out;
}

async function main(): Promise<void> {
  const res = await fetch(SOURCE);
  if (!res.ok) throw new Error(`fetch failed: ${res.status}`);
  const topology = JSON.parse(await res.text());
  const fc = feature(topology, topology.objects.countries) as unknown as {
    features: Feature[];
  };

  const entries: string[] = [];
  let rings = 0;
  let points = 0;

  for (const g of fc.features) {
    const name = g.properties?.name ?? '';
    if (SKIP.has(name)) continue;
    const shape = toRings(g.geometry);
    if (shape.length === 0) continue;
    rings += shape.length;
    points += shape.reduce((sum, r) => sum + r.length, 0);
    entries.push(`${name}${SEP}${JSON.stringify(shape)}`);
  }

  entries.sort();

  const body = `// Generated by scripts/build-world.ts. Do not edit by hand.
// Source: Natural Earth 110m via world-atlas (public domain).
// ${entries.length} countries, ${rings} rings, ${points} points. Coordinates rounded to 0.1 degrees.

export interface CountryShape {
  readonly name: string;
  readonly rings: readonly (readonly (readonly [number, number])[])[];
}

const SEP = ${JSON.stringify(SEP)};

const RAW: readonly string[] = [
${entries.map((e) => `  ${JSON.stringify(e)},`).join('\n')}
];

export const COUNTRIES: readonly CountryShape[] = RAW.map((entry) => {
  const at = entry.indexOf(SEP);
  return { name: entry.slice(0, at), rings: JSON.parse(entry.slice(at + SEP.length)) as CountryShape['rings'] };
});

const BY_NAME = new Map(COUNTRIES.map((c) => [c.name, c]));

export const countryByName = (name: string): CountryShape | undefined => BY_NAME.get(name);
`;

  writeFileSync(OUT, body, 'utf8');
  console.log(`wrote ${entries.length} countries, ${rings} rings, ${points} points`);
}

void main();
